# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: pranavjames/Certification-Github-Actions/.github/workflows/reusable_workflow.yml@main  # Call the reusable workflow
    # ./.github/workflows/reusable_workflow.yml
    with:
      message: 'Hello from the calling another workflow!'
