name: Default env variables, accessing secrets, environment_variables

on:
  push:  
  workflow_dispatch:

env:
    env1: "Workflow Level env"
    wenv: "wenv for workflow env"
jobs:
    
    job1:
        runs-on: ubuntu-latest
        env:
            env1: "Job level env"
            jenv: "JENV for Job"
        steps:
            - name: Github Context Variables    
              run: |
                echo " $GITHUB_EVENT_NAME "
                echo " $GITHUB_RUN_NUMBER "
                echo "workflow: ${{ github.workflow }}"                
                echo "run_id: ${{ github.run_id }}"
                echo "actor: ${{ github.actor }}"
                echo "event_name: ${{ github.event_name }}"
                echo "api_url: ${{ github.api_url }}"
                echo "repository: ${{ github.repository }}"
                echo "action: ${{ github.action }}"
                echo "sha: ${{ github.sha }}"
                # echo "head_ref: ${{ github.head_ref }}"                
                echo "event_path: ${{ github.event_path }}"
                echo "job name: ${{github.job}}"
            
            - name: Runner Environment Variables
              run: |
            
                echo "os: ${{runner.os}}"
                echo "temp: ${{runner.temp}}"
                echo "workspace ${{runner.workspace}}"
                echo "runner_name ${{runner.name}}"
                echo "runner environment: $RUNNER_ENVIRONMENT "
                echo "runner_tool_cache: $RUNNER_TOOL_CACHE "

            - name: Step-Level env variable
              env:
                env1: "my env"
              run: |
                 echo "Hi there ${{env.env1}}"
                 echo "$env1"
            
            - name: Accessing env variable
              run: |
                echo "Hi there ${{env.env1}}"
                echo "$env1"
                echo "-----------------------------"
                echo "workflow env ${{env.wenv}}"
                echo "$wenv"
                echo "-----------------------------"
                echo "job env ${{env.jenv}}"
                echo "$jenv"


            - name: Running a script
              uses: actions/github-script@v5
              with:
                script: |
                  console.log('Hello from GitHub Actions!');    


               
