name: Use Composite Action

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  use_print_message_action:
    runs-on: ubuntu-latest
    steps:
      - name: Call Print Message Action
        uses: pranavjames/Certification-Github-Actions/.github/actions/print-message # Reference the composite action
        with:
          message: "Hello from the composite action!"
