on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the environment to run the job on
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository code

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Set the Java version (you can change it to another version if needed)
        distribution: 'adoptopenjdk'  # You can change the distribution as needed
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository  # Path to Maven dependencies
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key based on pom.xml file
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install  # Run Maven to build the project

    - name: Run Tests
      run: mvn test  # Run the tests with Maven
