name: Workflow 2 - Deploy
on:  
   workflow_run:    
     workflows: ["Workflow 1 - Run Tests"]  # Name of the first workflow    
     types:      
       - completed
#       - requested: The workflow run was requested but hasn't started yet (this is less common in most workflows).
#       - queued: The workflow run is queued and waiting to start.
jobs:  
  deploy:    
    runs-on: ubuntu-latest    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Check if Workflow 1 was successful    
    steps:      
      - name: Deploy the application        
        run: |          
          echo "Deploying the application because Workflow 1 passed." 