on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
      - 'sub-project/**'
      - '!sub-project/docs/**'
    branches-ignore:
      - 'mona/octocat'
      - 'releases/**-alpha'
    tags-ignore:
      - 'v2'
      - 'v1.*'
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      description:
        description: 'Description of the input file'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test
